name: Java CI

on: [push]

jobs:
  run-rewrite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Initial build
      run: ./mvnw package
    - name: Openrewrite with Maven
      run: ./mvnw
             --no-transfer-progress
             --show-version
             rewrite:run
    - name: Show applied changes
      run: git status && git diff
    - name: Recompile after rewrite made changes
      run: ./mvnw compile
